language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test package publishOnlyWhenOnMaster
scala:
  - 2.11.1
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk8
notifications:
  email:
    - eugene.burmako@epfl.ch
env:
  global:
   - SCALAMACROS_MAVEN_REALM="Sonatype Nexus Repository Manager"
   - SCALAMACROS_MAVEN_DOMAIN="oss.sonatype.org"
   - secure: "HAUyJIcG3b7hlazDVsMY7rLWwSzpZ11wWA9qpMtQb5Thumu2h5BnDM081dXFSakuwYXbdUAKk5OMiUa4SeWHDMmR6IsuN8MS5HTC0OefIuJW+C+tuf/uL5SzknRpL4VdGJb9FActMHkGrn5HICL/Br0f0yOfHH3J4jFYDYNSFHs="
   - secure: "aN7Rdyypnht5fPwpMXnDxCGSYi6reGtIq3g51+m9FbJRaAGg8w1zCuUia/u5ASDKWMGvVjQ/wl6OEMVMd73H2E5BPRIOhRS2I6ZPYwEIUADE+uT9MKrOUxdgI1BlxWiPZRnrlvll9+y3xFl7Q+buDUWvrIBqSDBJ30gE/DL5n24="
